git:
  depth: 5

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - libcurl4-openssl-dev # required to avoid SSL errors

language: ruby

rvm:
  - 2.4

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - gem install html-proofer

install:
  - bundle install --retry 3 --clean --path vendor/bundle && htmlproofer _site/

script:
  - bundle exec jekyll build

matrix:
  fast_finish: true

cache:
  directories:
    - vendor/bundle
