git:
  depth: 5

sudo: false

dist: trusty

addons:
  apt:
    packages:
      - libcurl4-openssl-dev # required to avoid SSL errors

language: ruby

rvm:
  - 2.4

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - bundle install --retry 3 --clean --path vendor/bundle
  - gem install html-proofer

script:
  - bundle exec jekyll build
  - htmlproofer _site/ --check-external-hash --check-favicon --check-html --check-img-http --check-opengraph --empty-alt-ignore --enforce-https --report-missing-names --report-script-embeds --internal-domains sustainoss.org

matrix:
  fast_finish: true

cache:
  directories:
    - vendor/bundle

notifications:
  email: false
