name:               "SustainUK 2018"
description:        "A one day event for Open Source sustainers"

markdown:           kramdown

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# permalinks
permalink:          pretty

sass:
  style:            compressed

# server
source:             "."
destination:        ./_site/
port:               8000
url:                "https://sustainoss.org"
encoding:           UTF-8

exclude:
  - archives/
  - assets/ai/
  - assets/logo/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - "*.ai"
  - "*.eps"

params:
  twitter_handle:   "@SustainOSS"
  twitter:          "https://twitter.com/SustainOSS"
  github:           "https://github.com/sustainers"
  slack:            "https://changelog.slack.com/"
  latitude:         51.5160862
  longitude:        -0.127264

defaults:
  -
    scope:
      path:         "assets/**/*.pdf"
    values:
      sitemap:      false
