name:               Sustain
description:        a one day conversation for open source software sustainers

markdown:           kramdown

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

# permalinks
permalink:          pretty

sass:
  style:            compressed

# server
port:               8000
url:                https://sustainoss.org
encoding:           UTF-8
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - archives/
  - assets/ai/
  - assets/logo/
  - "*.ai"
  - "*.eps"

assets:
  jquery: "https://code.jquery.com/jquery-3.3.1.slim.min.js"
  jquery_integrity: "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  bootstrapBundle: "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"
  bootstrapBundleIntegrity: "sha384-u/bQvRA/1bobcXlcEYpsEdFVK/vJs3+T+nXLsBYJthmdBuavHvAW6UsmqO2Gd/F9"

defaults:
  -
    scope:
      path:         "assets/**/*.pdf"
    values:
      sitemap:      false
